FROM ubuntu:jammy
FROM python:3.11

COPY requirements.txt ./

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

ADD srv .

CMD ["python", "./main.py", "--api", "172.17.0.1", "--irc", "172.17.0.1"]

EXPOSE 34001/tcp
EXPOSE 34000/udp