version: '3.8'

services:

  srv:
    context: .
    dockerfile: dockerfile.srv
    ports:
      - "34001:34001"
      - "34000:34000"
    networks:
      - dmcr

  db:
    context: .
    dockerfile: dockerfile.db
    expose:
      - 8000
    environment:
      HOST: database
      USERNAME: DMCR
      PASSWORD: changeme
    networks:
      dmcr:
        aliases:
          - database

  irc:
    context: .
    dockerfile: dockerfile.irc
    ports:
      - "6667:6667"
    networks:
      dmcr:
        aliases:
          - irc

networks:
  dmcr: