FROM ubuntu:jammy
FROM python:3.11

COPY requirements.txt ./

RUN pip install --no-cache-dir --upgrade pip \
&& pip install --no-cache-dir -r requirements.txt

ADD . .

CMD ["sh", "-c", \
"python ./main.py \
--irc_address 192.168.0.200 \
--api_address ${API_HOST} \
--db_address ${DATABASE_HOST} \
--db_username ${DATABASE_USER} \
--db_password ${DATABASE_PASS}"]
# "--irc", "172.17.0.1"]

EXPOSE 34001/tcp
EXPOSE 34000/udp