def change_account2(options: dict) -> str:
    return "".join((
        f"#ebox[%EBG](x:0,y:0,w:1024,h:768) ",
        f"#edit[%E_CUP](%EBG[x:0,y:0,w:0,h:0],{{%GV_CLANS_LAST_UPDATE}}) ",
        f"#exec(LW_cfile&\\00&Cookies/%GV_VE_NICK) ",
        f"#exec(LW_cfile&\\00&Cookies/%GV_VE_PASS) ",
        f"#exec(LW_cfile&\\00&Cookies/%GV_VE_GMID) ",
        f"#exec(LW_cfile&\\00&Cookies/%GV_VE_AC) ",
        f"#block(cancel.cml,l_g):<!goback!>\\00 ",
        f"#end(l_g) ",
        f"#table[%TBL](%EBG[x:251,y:247,w:523,h:381],{{}}{{}}{{GW|open&change.dcml\\00&cansel=true^accounts=^VE_NICK=<%GV_VE_NICK>^VE_GMID=<%GV_VE_GMID>^VE_PASS=<%GV_VE_PASS>^icon_last_update=<%GV_CLANS_LAST_UPDATE>^save_pass=<%GV_SAVE_PASS>\\00|LW_lockall}}{{LW_file&Internet/Cash/cancel.cml}},3,-1,1,2,11,368,\"OLD PROFILE\",,26,\"Login\",\"Cancel\")",
        f"#ebox[%LBX](x:270,y:143,w:500,h:220) ",
        f"#pix[%PX2](%LBX[x:4,y:195,w:100%,h:100%],{{}},Internet/pix/i_pri0,35,35,35,35) ",
        f"#font(BC14,BC14,BC14) ",
        f"#txt[%L_NICK](%LBX[x:4,y:234,w:100%,h:20],{{}},\"Nickname\") ",
        f"#pan[%P_NICK](%LBX[x:151,y:234,w:324,h:14],1) ",
        f"#edit[%E_NICK](%LBX[x:156,y:231,w:302,h:18],{{%GV_VE_NICK}},0,0,0,1) ",
        f"#txt[%L_PASS](%LBX[x:4,y:265,w:100%,h:20],{{}},\"User Password\") ",
        f"#pan[%P_PASS](%LBX[x:151,y:265,w:324,h:14],1) ",
        f"#edit[%E_PASS](%LBX[x:156,y:262,w:302,h:20],{{%GV_VE_PASS}},0,0,1) ",
        f"#txt[%L_BOXID](%LBX[x:4,y:296,w:100%,h:20],{{}},\"Game Box #ID\") ",
        f"#pan[%P_BOXID](%LBX[x:151,y:296,w:324,h:14],1) ",
        f"#edit[%E_BOXID](%LBX[x:156,y:293,w:302,h:20],{{%GV_VE_GMID}},0,0,1) ",
        f"#pix[%PX3](%LBX[x:4,y:317,w:100%,h:100%],{{}},Internet/pix/i_pri0,35,35,35,35) ",
        f"#chk[%E_SAVE](%LBX[x:4,y:351,w:302,h:20],{{%GV_SAVE_PASS}},\"  Save password\",0,1,0) ",
        f"#hint(%L_NICK,\"Enter your nickname\") ",
        f"#hint(%L_PASS,\"Enter your password\") ",
        f"#hint(%L_BOXID,\"Enter your GameBox ID#\") ",
        f"#hint(%T_DELETE,\"Delete account\") ",
        f"#hint(%E_SAVE,\"This option saves your password and Game Box #ID. Don't use it, if you play from computer accessible for other people.\") ",
        f"<MESDLG> ",
        f"<MESDLG> ",
        f"#block(l_games_btn.cml,CAN)<MESDLG><MESDLG> ",
        f"#end(CAN)",
    ))