def change_account2() -> str:
    return "".join((
        f"#ebox[%EBG](x:0,y:0,w:1024,h:768)",
        f"#edit[%E_CUP](%EBG[x:0,y:0,w:0,h:0],{{%GV_CLANS_LAST_UPDATE}})",
        f"#exec(LW_cfile&\\00&Cookies/%GV_VE_NICK)",
        f"#exec(LW_cfile&\\00&Cookies/%GV_VE_PASS)",
        f"#exec(LW_cfile&\\00&Cookies/%GV_VE_GMID)",
        f"#exec(LW_cfile&\\00&Cookies/%GV_VE_AC)",
        f"#table[%TBL](%EBG[x:240,y:217,w:540,h:392],{{}}{{}}{{GW|open&change.dcml\\00&cansel=true^accounts=^VE_NICK=<%GV_VE_NICK>^VE_GMID=<%GV_VE_GMID>^VE_PASS=<%GV_VE_PASS>^icon_last_update=<%GV_CLANS_LAST_UPDATE>^save_pass=<%GV_SAVE_PASS>\\00|LW_lockall}}{{LW_key&#CANCEL}},2,-1,1,0,477,\"OLD PROFILE\",,24,\"Login\",\"Cancel\")",
        f"#def_dtbl_button_hint(,,) #ebox[%LBX](x:260,y:200,w:500,h:220)",
        f"#font(BC14,BC14,BC14)",
        f"#txt[%L_NICK](%LBX[x:4,y:220,w:100%,h:20],{{}},\"Nickname\")",
        f"#pan[%P_NICK](%LBX[x:183,y:217,w:310,h:18],3)",
        f"#edit[%E_NICK](%LBX[x:187,y:217,w:302,h:20],{{%GV_VE_NICK}},0,0,0,1)",
        f"#txt[%L_PASS](%LBX[x:4,y:253,w:100%,h:20],{{}},\"User Password\")",
        f"#pan[%P_PASS](%LBX[x:183,y:250,w:310,h:18],3)",
        f"#edit[%E_PASS](%LBX[x:187,y:250,w:302,h:20],{{%GV_VE_PASS}},0,0,1)",
        f"#txt[%L_BOXID](%LBX[x:4,y:286,w:100%,h:20],{{}},\"Game Box #ID\")",
        f"#pan[%P_BOXID](%LBX[x:183,y:283,w:310,h:18],3)",
        f"#edit[%E_BOXID](%LBX[x:187,y:283,w:302,h:20],{{%GV_VE_GMID}},0,0,1)",
        f"#pan[%P_PROF](%LBX[x:22,y:42,w:460,h:120],3)",
        f"#pix[%PX2](%LBX[x:20,y:40,w:100%,h:100%],{{}},Interf3/InGame/_common_pictures,2,2,2,2)",
        f"#chk[%E_SAVE](%LBX[x:4,y:331,w:302,h:20],{{%GV_SAVE_PASS}},\" Save password\",0,1,0)",
        f"#hint(%L_NICK,\"Enter your nickname\")",
        f"#hint(%L_PASS,\"Enter your password\")",
        f"#hint(%L_BOXID,\"Enter your GameBox ID#\")",
        f"#hint(%T_DELETE,\"Delete account\")",
        f"#hint(%E_SAVE,\"This option saves your password and Game Box #ID. Don\'t use it, if you play from computer accessible for other people.\")",
        f"#def_dtbl_button(Internet/pix/i_pri1,45,46,-1,-2,0,2,1)",
        f"<MESDLG>",
        f"<MESDLG>",
        f"#block(l_games_btn.cml,CAN)",
        f"<MESDLG>",
        f"<MESDLG>",
        f"#end(CAN)"
    ))